[project]
name = "sh-hk-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=45.0.5",
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
]
